version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing serverless CLI
      - npm i -g serverless@3
      - cd notes-crud-api/notes
      - echo Installing npm dependencies of notes service
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo Deploying resources
      - serverless deploy --stage dev
artifacts:
  files:
    - notes-crud-api/notes/my-artifact/*
  name: MyProjectArtifact
cache:
  paths:
    - 'notes-crud-api/notes/node_modules/**/*'
