# notes dynamoDB table
notesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: notesId
        AttributeType: S
    KeySchema:
      - AttributeName: notesId
        KeyType: HASH

#Cognito user pool
cognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: notesUserPool

# user pool web client
cognitoUserPoolWebClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId: !Ref cognitoUserPool
    ClientName: web

#cognito user pool domain
cognitoUserPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties: 
    UserPoolId: !Ref cognitoUserPool 
    Domain: emilynotescd

# application parameters
userPoolIdParam:
  Type: AWS::SSM::Parameter
  Properties: 
    Name: /notes/dev/userPoolId
    Type: String
    Value: !GetAtt cognitoUserPool.Arn